version: '3'

services:
  haproxy:
    container_name: haproxy
    image: haproxy:2.0
    restart: always
    volumes:
      - ./haproxy/bind:/usr/local/etc/haproxy:ro,Z
      - letsencrypt_etc:/etc/letsencrypt:ro
    networks:
      - haproxy
    ports:
      - 80:8080
      - 443:8443
    user: '1001'
    
volumes:
  letsencrypt_etc:
    
networks:
  haproxy: